### ISSUE TITLE
EventMemory has problems

### ISSUE THREAD

**Issue by 12345ieee** [epol/acts#2]
I'm in a hurry, I just copypaste the chat lines, if needed I'll refine the exposition later.

22:03:44 - Io: devi esporre quanti elementi ha la eventmemory
22:04:13 - Io: o io metto un loop da 0 a 10 e nelle prime 9 iterazioni raccolgo garbage
22:07:25 - Io: oltre al fatto che (-1)%N fa -1, il che mada tutto a troie
22:07:32 - Io: *manda
22:08:02 - Io: (N!=0,1, perchè te sei un matematico)

**Comment by epol** [comment]
- The number of events in EventMemory is returned by the method int size()
- the negative module was a ugly bug. It should have been fixed in commit f034005.

I'm closing the issue, feel free to reopen it if the fix is not satisfactory.
